[project]
name = "ckip-transformers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.24.0",
    "torch>=1.5.1",
    "tqdm>=4.64.1",
    "transformers>=4.52.4",
]
